name: Feature Request
description: Suggest a new feature or enhancement for this project.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a feature!
        Please fill out the details below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem will this feature solve? Why is it important?
      placeholder: Ex. It's difficult to track user activity because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Please describe your ideal solution or feature.
      placeholder: Ex. Add an activity dashboard with filtering options.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, mockups, screenshots, or context?
      placeholder: Ex. Links, screenshots, related issues, etc.
    validations:
      required: false
