name: Update Azure DevOps Work Items on Commit

# This workflow moves referenced ADO work items to 'Doing' only on the first commit to a branch.
# This prevents circumventing other state transitions when making subsequent commits.
on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  update-ado-workitem-commit:
    uses: ./.github/workflows/update-ado-workitems.yml
    with:
      trigger_type: 'commit'
      target_state: 'Doing'
      branch_name: ${{ github.ref_name }}
      commit_sha: ${{ github.sha }}
      commit_before_sha: ${{ github.event.before }}
      commit_messages: ${{ toJSON(github.event.commits[*].message) }}
    # Secrets are optional - if not passed, the reusable workflow will use 
    # organizational or repository secrets directly
    secrets:
      ADO_ORG_URL: ${{ secrets.ADO_ORG_URL }}
      ADO_PAT: ${{ secrets.ADO_PAT }}
      ADO_PROJECT: ${{ secrets.ADO_PROJECT }}
